version: '3.9'
services:
  it-tools:
    container_name: it-tools
    image: ghcr.io/sharevb/it-tools:2026.7.11@sha256:eb3851fd899f52f6eb5f6539257555df041554f8078c2c71c56355ab6cd399cb
    restart: unless-stopped
    networks:
      cfd-bridge:
    logging:
      # prevent bots from overloading logging
      driver: "none"

networks:
  cfd-bridge:
    external: true
