services:
  scrypted:
    container_name: scrypted
    image: ghcr.io/koush/scrypted:v0.143.0-noble-full@sha256:205bc8f6c3d8a3a87bb65a6ed411c105a5ba0cce6cdd4e50219e3227c99cacb9
    restart: unless-stopped
    environment:
      - SCRYPTED_DOCKER_AVAHI=true
    volumes:
      - $BUILTIN__APP_DATA_HOST_PATH/scrypted:/server/volume:rw
    networks:
      home-macvlan:
        ipv4_address: 192.168.20.230
      home-bridge:
      cctv-macvlan:
        ipv4_address: 192.168.120.230
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=home-bridge"
        - "traefik.http.routers.scrypted.rule=Host(`scrypted.$BUILTIN__BASE_DOMAIN`)"
        - "traefik.http.services.scrypted.loadbalancer.server.port=11080"

networks:
  home-macvlan:
    external: true
  home-bridge:
    external: true
  cctv-macvlan:
    external: true
