version: '3.8'

services:
  beszel-hub:
    image: ghcr.io/henrygd/beszel/beszel:0.19.0@sha256:03ab07ea808d65c1153ebd554ac456063ae5586a659c7ad69511d6bc31d98287
    container_name: beszel-hub
    restart: unless-stopped
    user: "1005:3008" # Run as beszel user for proper permissions with mounted volume
    volumes:
      - $BUILTIN__APP_DATA_HOST_PATH/beszel:/beszel_data # create a dataset for this
    networks:
      - mgmt-bridge
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mgmt-bridge"
      - "traefik.http.routers.beszel.rule=Host(`beszel.$BUILTIN__BASE_DOMAIN`)"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"
      # Note: Disable HTTP/3 for Beszel if you encounter websocket issues
      # - "traefik.http.middlewares.beszel-no-http3.headers.customresponseheaders.alt-svc=clear"
      # - "traefik.http.routers.beszel.middlewares=beszel-no-http3@docker"

  beszel-agent:
    image: ghcr.io/henrygd/beszel/beszel-agent-intel:0.19.0@sha256:b590af80e9e8dbf964386789153238925c5142d68fa73274435ce8de56cd7432
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    privileged: true
    cap_add:
      - CAP_PERFMON
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $BUILTIN__APP_DATA_HOST_PATH/beszel-agent:/var/lib/beszel-agent
      - /:/host:ro # Access host metrics from within container
    environment:
      LISTEN: 45876
      KEY: '$SECRET__AGENT_KEY'
      TOKEN: '$SECRET__AGENT_TOKEN'
      HUB_URL: https://beszel.gunzy.xyz # This is traefik on mgmt-bridge so is accessible from host network
    devices:
      - /dev/dri:/dev/dri # for intel GPU monitoring


networks:
  mgmt-bridge:
    external: true
